import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    Main main = new Main();
    @Test
    void convert() {
        String s0 = "[ E(a,b) ] -> [ W(b,c) ]";
        String s1 = "[ E(a,b) ] -> [ [ W(b,c) ] -> [ dE(c,d) ] ]";
        String s2 = "~ [ ~ [ E(a,b) ] ]";
        String s3 = "~ [ ~ [ ~ [ E(a,b) ] ] ]";
        String s4 = "~ [ [ E(a,b) ] & [ W(b,c) ] ]";
        String s5 = "~ [ [ E(a,b) ] | [ W(b,c) ] ]";
        String s6 = "[ E(a,b) ] & [ [ W(b,c) ] | [ N(c,d) ] ]";
        String s7 = "[ [ E(a,b) ] | [ W(b,c) ] ] & [ N(c,d) ]";
        String s8 = "[ E(a,b) ] | [ E(a,b) ]";
        String s9 = "[ E(a,b) ] & [ E(a,b) ]";
        String s10 = "[ E(a,b) ] & [ ~ [ E(a,b) ] ]";
        String s11 = "[ E(a,b) ] | [ ~ [ E(a,b) ] ]";
        String s12 = "~ [ T ]";
        String s13 = "~ [ F ]";
        String s14 = "[ [ a ] | [ b ] ] & [ [ c ] | [ d ] ]";
        String s15 = "[ [ a ] & [ b ] ] | [ [ c ] & [ d ] ]";
        String s16 = "~ [ ~ [ ~ [ ~ [ [ [ a ] & [ b ] ] | [ [ c ] & [ d ] ] ] ] ] ]";
        String s17 = "~ [ [ [ E(a,b) ] & [ W(b,c) ] ] | [ [ E(a,b) ] & [ N(c,d) ] ] ]";
        String s18 = "~ [ [ ~ [ E(a,b) ] ] & [ W(b,c) ] ]";
        String s19 = "[ E(a,b) ] -> [ [ W(b,c) ] -> [ W(a,b) ] ]";
        String s20 = "[ [ E(a,b) ] & [ W(a,b) ] ] & [ I(a,b) ]";
        String s21 = "~ [ [ ~ [ E(a,b) ] ] & [ ~ [ E(a,b) ] ] ]";
        String s22 = "~ [ [ ~ [ E(a,b) ] ] & [ ~ [ W(b,c) ] ] ]";
        String s23 = "[ ~ [ E(a,b) ] ] | [ W(b,c) ]";
        String s24 = "~ [ [ ~ [ ~ [ E(a,b) ] ] ] -> [ ~ [ W(b,c) ] ] ]";
        String s25 = "~ [ ~ [ ~ [ [ E(a,b) ] & [ Inew(b,c) ] ] ] ]";
        String s26 ="[ E(a,b) ] & [ [ [ [ E(a,b) ] | [ E(a,b) ] ] & [ E(b,c) ] ] | [ W(b,c) ] ]";
        String s27 = "[ a ] & [ [ [ [ a ] | [ a ] ] & [ b ] ] | [ c ] ]";
        String s29 = "~ [ [ ~ [ a ] ] -> [ b ] ]";
        String s30 = "[ E(a,b) ] -> [ [ W(b,c) ] -> [ W(b,c) ] ]";
        String s31 = "[ [ E(a,b) ] & [ E(a,b) ] ] | [ ~ [ E(a,b) ] ]";
        String s32 = "[ [ a ] | [ b ] ] & [ ~ [ [ a ] | [ b ] ] ]";
        String s33 = "[ [ a ] | [ b ] ] | [ [ a ] | [ c ] ]";
        String s34 = "[ [ a ] -> [ b ] ] -> [ [ a ] -> [ c ] ]";
        String s35 = "[ [ a ] | [ b ] ] & [ [ b ] | [ a ] ]";
        String s36 = "[ [ a ] | [ b ] ] & [ [ a ] | [ c ] ]";
        String s37 = "[ [ ~ [ a ] ] | [ b ] ] & [ a ]";
        String s38 = "[ ~ [ a ] ] & [ ~ [ a ] ]";
        String s39 = "[ E(a,b) ] -> [ ~ [ E(a,b) ] ]";
        String s40 = "[ E(a,b) ] -> [ ~ [ W(a,b) ] ]";
        String s41 = "~ [ [ E(a,b) ] & [ ~ [ E(a,b) ] ] ]";
        String s42 = "[ [ [ E(a,b) ] & [ W(b,c) ] ] & [ [ F(a,b) ] & [ S(b,c) ] ] ] | [ [ E(a,b) ] & [ N(c,d) ] ]";
        String s43 = "[ [ E(a,b) ] -> [ W(b,c) ] ] & [ ~ [ ~ [ E(a,b) ] ] ]";


        String s0o = "[ ~ [ E(a,b) ] ] | [ W(b,c) ]";
        String s1o = "[ ~ [ E(a,b) ] ] | [ [ ~ [ W(b,c) ] ] | [ dE(c,d) ] ]";
        String s2o = "E(a,b)";
        String s3o = "~ [ E(a,b) ]";
        String s4o = "[ ~ [ E(a,b) ] ] | [ ~ [ W(b,c) ] ]";
        String s5o = "[ ~ [ E(a,b) ] ] & [ ~ [ W(b,c) ] ]";
        String s6o = "[ [ E(a,b) ] & [ W(b,c) ] ] | [ [ E(a,b) ] & [ N(c,d) ] ]";
        String s7o = "[ [ E(a,b) ] & [ N(c,d) ] ] | [ [ W(b,c) ] & [ N(c,d) ] ]";
        String s8o = "E(a,b)";
        String s9o = "E(a,b)";
        String s10o = "F";
        String s11o = "T";
        String s12o = "F";
        String s13o = "T";
        String s14o = "[ [ [ a ] & [ c ] ] | [ [ b ] & [ c ] ] ] | [ [ [ a ] & [ d ] ] | [ [ b ] & [ d ] ] ]";
        String s15o = "[ [ a ] & [ b ] ] | [ [ c ] & [ d ] ]";
        String s16o = "[ [ a ] & [ b ] ] | [ [ c ] & [ d ] ]";
        String s17o = "[ [ ~ [ E(a,b) ] ] | [ [ ~ [ W(b,c) ] ] & [ ~ [ E(a,b) ] ] ] ] | [ [ [ ~ [ E(a,b) ] ] & [ ~ [ N(c,d) ] ] ] | [ [ ~ [ W(b,c) ] ] & [ ~ [ N(c,d) ] ] ] ]";
        String s18o = "[ E(a,b) ] | [ ~ [ W(b,c) ] ]";
        String s19o = "[ ~ [ E(a,b) ] ] | [ [ ~ [ W(b,c) ] ] | [ W(a,b) ] ]";
        String s20o = "[ [ E(a,b) ] & [ W(a,b) ] ] & [ I(a,b) ]";
        String s21o = "E(a,b)";
        String s22o = "[ E(a,b) ] | [ W(b,c) ]";
        String s23o = "[ ~ [ E(a,b) ] ] | [ W(b,c) ]";
        String s24o = "[ E(a,b) ] & [ W(b,c) ]";
        String s25o = "[ ~ [ E(a,b) ] ] | [ ~ [ Inew(b,c) ] ]";
        String s26o = "[ [ E(a,b) ] & [ E(b,c) ] ] | [ [ E(a,b) ] & [ W(b,c) ] ]";
        String s27o = "[ [ a ] & [ b ] ] | [ [ a ] & [ c ] ]";
        String s29o = "[ ~ [ a ] ] & [ ~ [ b ] ]";
        String s30o = "T";
        String s31o = "T";
        String s32o = "F";
        String s33o = "[ [ a ] | [ b ] ] | [ c ]";
        String s34o = "[ [ a ] & [ ~ [ b ] ] ] | [ [ ~ [ a ] ] | [ c ] ]";
        String s35o = "[ a ] | [ b ]";
        String s36o = "[ [ a ] | [ [ b ] & [ a ] ] ] | [ [ [ a ] & [ c ] ] | [ [ b ] & [ c ] ] ]";
        String s37o = "[ b ] & [ a ]";
        String s38o = "~ [ a ]";
        String s39o = "~ [ E(a,b) ]";
        String s40o = "[ ~ [ E(a,b) ] ] | [ ~ [ W(a,b) ] ]";
        String s41o = "T";
        String s42o = "[ [ [ E(a,b) ] & [ W(b,c) ] ] & [ [ F(a,b) ] & [ S(b,c) ] ] ] | [ [ E(a,b) ] & [ N(c,d) ] ]";
        String s43o = "[ W(b,c) ] & [ E(a,b) ]";


        assertEquals(s0o,main.convert(s0));
        assertEquals(s1o,main.convert(s1));
        assertEquals(s2o,main.convert(s2));
        assertEquals(s3o,main.convert(s3));
        assertEquals(s4o,main.convert(s4));
        assertEquals(s5o,main.convert(s5));
        assertEquals(s6o,main.convert(s6));
        assertEquals(s7o,main.convert(s7));
        assertEquals(s8o,main.convert(s8));
        assertEquals(s9o,main.convert(s9));
        assertEquals(s10o,main.convert(s10));
        assertEquals(s11o,main.convert(s11));
        assertEquals(s12o,main.convert(s12));
        assertEquals(s13o,main.convert(s13));
        assertEquals(s14o,main.convert(s14));
        assertEquals(s15o,main.convert(s15));
        assertEquals(s16o,main.convert(s16));
        assertEquals(s17o,main.convert(s17));
        assertEquals(s18o,main.convert(s18));
        assertEquals(s19o,main.convert(s19));
        assertEquals(s20o,main.convert(s20));
        assertEquals(s21o,main.convert(s21));
        assertEquals(s22o,main.convert(s22));
        assertEquals(s23o,main.convert(s23));
        assertEquals(s24o,main.convert(s24));
        assertEquals(s25o,main.convert(s25));
        assertEquals(s26o,main.convert(s26));
        assertEquals(s27o,main.convert(s27));
        assertEquals(s29o,main.convert(s29));
        assertEquals(s30o,main.convert(s30));
        assertEquals(s31o,main.convert(s31));
        assertEquals(s32o,main.convert(s32));
//        assertEquals(s33o,main.convert(s33));
        assertEquals(s34o,main.convert(s34));
        assertEquals(s35o,main.convert(s35));
        assertEquals(s36o,main.convert(s36));
        assertEquals(s37o,main.convert(s37));
        assertEquals(s38o,main.convert(s38));
        assertEquals(s39o,main.convert(s39));
        assertEquals(s40o,main.convert(s40));
        assertEquals(s41o,main.convert(s41));
        assertEquals(s42o,main.convert(s42));
        assertEquals(s43o,main.convert(s43));
    }
}